-- =========================================================
-- CINE UTN - ESQUEMA BASE SUPABASE
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'customer'
    check (role in ('customer', 'admin', 'staff')),
  credit numeric(12,2) not null default 0,
  loyalty_points integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text not null,
  synopsis text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  genres text[] not null default '{}',
  age_rating text not null,
  formats text[] not null default '{}',
  language_modes text[] not null default '{}',
  release_date date not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  rows_count integer not null check (rows_count > 0),
  seats_per_row integer not null check (seats_per_row > 0),
  active boolean not null default true
);

create table if not exists public.seats (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  row_code text not null,
  seat_number integer not null,
  accessible boolean not null default false,
  vip boolean not null default false,
  unique(room_id, row_code, seat_number)
);

create table if not exists public.cinema_functions (
  id bigint generated by default as identity primary key,
  movie_id bigint not null references public.movies(id),
  room_id bigint not null references public.rooms(id),
  starts_at timestamptz not null,
  format text not null check (format in ('2D', '3D', '4D', '5D')),
  language_mode text not null check (language_mode in ('castellano', 'subtitulada')),
  base_price numeric(12,2) not null,
  presale_price numeric(12,2),
  active boolean not null default true
);

create table if not exists public.function_seats (
  id bigint generated by default as identity primary key,
  function_id bigint not null references public.cinema_functions(id) on delete cascade,
  seat_id bigint not null references public.seats(id) on delete cascade,
  status text not null default 'available' check (status in ('available', 'sold')),
  unique(function_id, seat_id)
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null,
  stock integer not null default 0,
  active boolean not null default true
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent numeric(5,2),
  discount_amount numeric(12,2),
  valid_from timestamptz not null,
  valid_until timestamptz not null,
  active boolean not null default true
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  total numeric(12,2) not null,
  status text not null default 'paid'
    check (status in ('pending', 'paid', 'cancelled', 'used')),
  qr_code uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  cancelled_at timestamptz
);

create table if not exists public.purchase_tickets (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.purchases(id) on delete cascade,
  function_id bigint not null references public.cinema_functions(id),
  function_seat_id bigint not null references public.function_seats(id),
  price numeric(12,2) not null,
  used_at timestamptz
);

create table if not exists public.purchase_products (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references public.purchases(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null,
  collected_at timestamptz
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  movie_id bigint not null references public.movies(id) on delete cascade,
  stars integer not null check (stars between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique(user_id, movie_id)
);

create table if not exists public.loyalty_movements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  points integer not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.rewards (
  id bigint generated by default as identity primary key,
  name text not null,
  points_cost integer not null check (points_cost > 0),
  active boolean not null default true
);

create table if not exists public.credit_movements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

-- RLS base
alter table public.profiles enable row level security;
alter table public.movies enable row level security;
alter table public.rooms enable row level security;
alter table public.seats enable row level security;
alter table public.cinema_functions enable row level security;
alter table public.function_seats enable row level security;
alter table public.products enable row level security;
alter table public.coupons enable row level security;
alter table public.purchases enable row level security;
alter table public.purchase_tickets enable row level security;
alter table public.purchase_products enable row level security;
alter table public.reviews enable row level security;
alter table public.loyalty_movements enable row level security;
alter table public.rewards enable row level security;
alter table public.credit_movements enable row level security;
alter table public.audit_logs enable row level security;

-- Public catalog read policies
create policy "movies public read" on public.movies
for select using (active = true);

create policy "rooms public read" on public.rooms
for select using (active = true);

create policy "seats public read" on public.seats
for select using (true);

create policy "functions public read" on public.cinema_functions
for select using (active = true);

create policy "function seats public read" on public.function_seats
for select using (true);

create policy "products public read" on public.products
for select using (active = true);

create policy "reviews public read" on public.reviews
for select using (true);

-- User profile access
create policy "profile own read" on public.profiles
for select to authenticated
using (id = auth.uid());

create policy "profile own update" on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "purchase own read" on public.purchases
for select to authenticated
using (user_id = auth.uid());

create policy "purchase ticket own read" on public.purchase_tickets
for select to authenticated
using (
  exists (
    select 1 from public.purchases p
    where p.id = purchase_id and p.user_id = auth.uid()
  )
);

create policy "purchase product own read" on public.purchase_products
for select to authenticated
using (
  exists (
    select 1 from public.purchases p
    where p.id = purchase_id and p.user_id = auth.uid()
  )
);

create policy "review own write" on public.reviews
for insert to authenticated
with check (user_id = auth.uid());

create policy "review own update" on public.reviews
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- Profile creation after signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, coalesce(new.email, ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- NOTE:
-- Purchase creation, seat locking, cancellation, QR validation,
-- audit logging and admin policies should be implemented with
-- PostgreSQL functions/RPC or secure server-side logic.
-- Do not trust only client-side checks for these operations.
